# ALLOW NONE

READY = 'READY'
MAINTENANCE = 'MAINTENANCE'
START = 'START'
STARTING = 'STARTING'
STARTED = 'STARTED'
STOPPING = 'STOPPING'
STOPPED = 'STOPPED'
EXCEPTION = 'EXCEPTION'

LOGIN: str = 'LOGIN'
LOGOUT: str = 'LOGOUT'
CLEAR: str = 'CLEAR'
CHAT: str = 'CHAT'
