{
 "title": "ServerJockey",
 "description": "Dashboard for the ServerJockey game server management system.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "process", "query": { "query": "label_values(process)" } }
  ]
 },
 "panels": [
  {
   "title": "Instance Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(process, module) (process_info{job=\"$job\", instance=\"$instance\", process=\"$process\"})"
    }
   ]
  },
  {
   "title": "Online Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "online_players{job=\"$job\", instance=\"$instance\", process=\"$process\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UP %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(process_info{job=\"$job\", instance=\"$instance\", process=\"$process\"}[$__range]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\", instance=\"$instance\", process=\"$process\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU used by process",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\", process=\"$process\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\", process=\"$process\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_read_bytes_total{job=\"$job\", instance=\"$instance\", process=\"$process\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_write_bytes_total{job=\"$job\", instance=\"$instance\", process=\"$process\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}